apiVersion: v1
kind: Service
metadata:
  name: doctor-service
spec:
  selector:
    app: doctor-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 31001