apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  labels:
    app: doctor-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          #          image: gcr.io/PROJECT_ID/IMAGE:TAG
          image: gcr.io/healthsync-444908/doctor-service-image:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb+srv://kaushalya20240321:UfYI8TLMUYhQGAMm@healthsync.0xamq.mongodb.net/?retryWrites=true&w=majority